/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    ClickRank: typeof import('./components/ClickRank.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NewBookRank: typeof import('./components/NewBookRank.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateRank: typeof import('./components/UpdateRank.vue')['default']
    WeekRecommend: typeof import('./components/WeekRecommend.vue')['default']
  }
}
